[package]
name = "blob"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
reqwest = { version = "0.12.4", features = ["json"] }
serde_json = "1.0.117"
tokio = { version = "1.37.0", features = ["full"] }
serde_derive = "1.0.203"
serde = "1.0.203"
git2 = "0.18.3"
chrono = { version = "0.4.38", features = ["serde"] }
dotenv = "0.15.0"
anyhow = "1.0.86"
futures = "0.3.30"
infer = "0.15.0"
rayon = "1.10.0"
crossbeam-utils = "0.8.20"
sha2 = "0.10.8"
